---
title: "StatsLab EDA"
author: "Jorge da Silva Gonçalves"
date: "21 3 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Load datasets

Version1
```{r}
altenrhein_v1 <- read.csv("../data/processed_normed_data_altenrhein_v1.csv", sep = ";")
chur_v1 <- read.csv("../data/processed_normed_data_chur_v1.csv", sep = ";")
geneve_v1 <- read.csv("../data/processed_normed_data_geneve_v1.csv", sep = ";")
laupen_v1 <- read.csv("../data/processed_normed_data_laupen_v1.csv", sep = ";")
lausanne <- read.csv("../data/processed_normed_data_lausanne.csv", sep = ";")
lugano_v1 <- read.csv("../data/processed_normed_data_lugano_v1.csv", sep = ";")
zurich_v1 <- read.csv("../data/processed_normed_data_zurich_v1.csv", sep = ";")
```


Version2 
```{r}
altenrhein_v2 <- read.csv("../data/processed_normed_data_altenrhein_v2.csv", sep = ";")
chur_v2 <- read.csv("../data/processed_normed_data_chur_v2.csv", sep = ";")
geneve_v2 <- read.csv("../data/processed_normed_data_geneve_v2.csv", sep = ";")
laupen_v2 <- read.csv("../data/processed_normed_data_laupen_v2.csv", sep = ";")
lausanne <- read.csv("../data/processed_normed_data_lausanne.csv", sep = ";")
lugano_v2 <- read.csv("../data/processed_normed_data_lugano_v2.csv", sep = ";")
zurich_v2 <- read.csv("../data/processed_normed_data_zurich_v2.csv", sep = ";")
```



```{r}
# get list of all loaded dataframes
df_list <- ls()[sapply(ls(), function(x) any(class(get(x)) == 'data.frame'))]
# display all vars over time for each table
for (df in df_list){
  par(mfrow = c(2,3))
  tab <- get(df)
  colnames(tab) <- c("date", "sars_cov2_rna", "median_7d_sars_cov2_rna",
                     "new_cases", "median_7d_new_cases", "quantification_flag", "flow")
  date <- as.Date(format(tab$date, format = "%y-%m-%d"))
  cols <- colnames(tab)[c(2:5, 7)]
  for (col in cols) {
    plot(date, tab[,col], xlab = "", ylab = col, main = df, type = "l")
  }
}

```


```{r}

```


```{r}

```


```{r}

```

